version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: lunch_vote_db
      POSTGRES_USER: lunch_user
      POSTGRES_PASSWORD: lunch_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      - db
    environment:
      DB_NAME: lunch_db
      DB_USER: lunch_user
      DB_PASSWORD: lunch_pass
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata:
